
TEAMS = [
    "Kansas",
    "Austin Peay",
    "Colorado",
    "UConn",
    "Maryland",
    "SouthDak\\u2026",
    "Cal",
    "Hawaii",
    "Arizona",
    "Wichita St.",
    "Miami",
    "Bu\\ufb00alo",
    "Iowa",
    "Temple",
    "Villanova",
    "UNCAshev\\u2026",
    "Oregon",
    "Holy Cross",
    "Saint Joe's",
    "Cincinnati",
    "Baylor",
    "Yale",
    "Duke",
    "UNCWilmi\\u2026",
    "Texas",
    "NorthernIo\\u2026",
    "Texas A&M",
    "Green Bay",
    "OregonSta\\u2026",
    "VCU",
    "Oklahoma",
    "CSUBaker\\u2026",
    "UNC",
    "FGCU",
    "USC",
    "Providence",
    "Indiana",
    "Chattanoo\\u2026",
    "Kentucky",
    "StonyBro\\u2026",
    "NotreDa\\u2026",
    "Michigan",
    "WestVirgi\\u2026",
    "SF Austin",
    "Wisconsin",
    "Pitt",
    "Xavier",
    "WeberSta\\u2026",
    "UVA",
    "Hampton",
    "Texas Tech",
    "Butler",
    "Purdue",
    "AR\\xadLittleR\\u2026",
    "Iowa State",
    "Iona",
    "Seton Hall",
    "Gonzaga",
    "Utah",
    "FresnoSta\\u2026",
    "Dayton",
    "Syracuse",
    "Michigan\\u2026",
    "MidTenn\\u2026"
]